/**
 * TypeScript types for the PerFi database schema.
 * Source: Phase 3 Section 5 + migration 002.
 *
 * These types mirror the Postgres schema and are used for type-safe
 * data access throughout the application. In production, these would
 * be auto-generated by `supabase gen types typescript` — this file
 * serves as the manual foundation until that workflow is set up.
 */

// ── Enum-like types ──

export type UserRole = 'user' | 'admin';
export type WorkspaceType = 'personal' | 'personal_household';
export type WorkspaceRole = 'owner' | 'member' | 'viewer';
export type AccountType = 'current' | 'savings' | 'credit_card' | 'cash' | 'investments';
export type CategoryType = 'expense' | 'income' | 'transfer';
export type TransactionType = 'expense' | 'income' | 'transfer';
export type IncomeSourceType = 'employment' | 'benefit' | 'other';
export type BenefitType =
  | 'universal_credit'
  | 'pip'
  | 'child_benefit'
  | 'carers_allowance'
  | 'esa'
  | 'housing_benefit'
  | 'council_tax_reduction'
  | 'other';
export type Frequency = 'weekly' | 'fortnightly' | 'four_weekly' | 'monthly';
export type BillFrequency = Frequency | 'annually';
export type PaymentMethod = 'direct_debit' | 'standing_order' | 'card' | 'manual';
export type PlanType = 'free' | 'pro';
export type SubscriptionStatus = 'active' | 'cancelled' | 'past_due' | 'expired';
export type GoalType = 'savings' | 'financial';
export type GoalStatus = 'active' | 'completed' | 'abandoned';
export type WaitlistStatus = 'pending' | 'invited' | 'converted';
export type ContactStatus = 'new' | 'read' | 'responded';

// ── Table row types ──

export interface Profile {
  id: string;
  display_name: string | null;
  onboarding_completed: boolean;
  onboarding_step: number;
  preferences: Record<string, unknown>;
  role: UserRole;
  is_disabled: boolean;
  created_at: string;
  updated_at: string;
}

export interface Subscription {
  id: string;
  user_id: string;
  stripe_customer_id: string | null;
  stripe_subscription_id: string | null;
  plan: PlanType;
  status: SubscriptionStatus;
  current_period_start: string | null;
  current_period_end: string | null;
  cancel_at_period_end: boolean;
  created_at: string;
  updated_at: string;
}

export interface Workspace {
  id: string;
  name: string;
  type: WorkspaceType;
  owner_id: string;
  is_demo: boolean;
  created_at: string;
  updated_at: string;
}

export interface WorkspaceMember {
  id: string;
  workspace_id: string;
  user_id: string;
  role: WorkspaceRole;
  created_at: string;
}

export interface Account {
  id: string;
  workspace_id: string;
  name: string;
  type: AccountType;
  balance: number;
  is_active: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface Category {
  id: string;
  workspace_id: string;
  name: string;
  type: CategoryType;
  icon: string | null;
  colour: string | null;
  is_default: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface Transaction {
  id: string;
  workspace_id: string;
  account_id: string;
  category_id: string | null;
  type: TransactionType;
  amount: number;
  description: string;
  date: string;
  notes: string | null;
  is_recurring: boolean;
  bill_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface IncomeSource {
  id: string;
  workspace_id: string;
  name: string;
  type: IncomeSourceType;
  benefit_type: BenefitType | null;
  amount: number;
  frequency: Frequency;
  next_pay_date: string;
  account_id: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface Bill {
  id: string;
  workspace_id: string;
  name: string;
  amount: number;
  frequency: BillFrequency;
  next_due_date: string;
  payment_method: PaymentMethod;
  account_id: string | null;
  category_id: string | null;
  is_subscription: boolean;
  is_active: boolean;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface Budget {
  id: string;
  workspace_id: string;
  category_id: string;
  amount: number;
  period: 'monthly';
  created_at: string;
  updated_at: string;
}

export interface Goal {
  id: string;
  workspace_id: string;
  name: string;
  type: GoalType;
  target_amount: number;
  current_amount: number;
  target_date: string | null;
  debt_id: string | null;
  category_id: string | null;
  status: GoalStatus;
  created_at: string;
  updated_at: string;
}

export interface GoalContribution {
  id: string;
  goal_id: string;
  workspace_id: string;
  amount: number;
  date: string;
  notes: string | null;
  created_at: string;
}

export interface Debt {
  id: string;
  workspace_id: string;
  name: string;
  account_id: string | null;
  balance: number;
  minimum_payment: number;
  interest_rate: number | null;
  next_payment_date: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface WaitlistEntry {
  id: string;
  email: string;
  interests: string[] | null;
  status: WaitlistStatus;
  invited_at: string | null;
  converted_at: string | null;
  created_at: string;
}

export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  message: string;
  status: ContactStatus;
  admin_notes: string | null;
  created_at: string;
}

export interface AdminNote {
  id: string;
  user_id: string;
  author_id: string;
  content: string;
  created_at: string;
}

export interface FeatureFlag {
  id: string;
  key: string;
  value: unknown;
  updated_at: string;
}
